<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="jQuery" Version="3.7.1" />
    <PackageReference Include="jQuery.Validation" Version="1.21.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.74.1" />
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Validation" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Views\" />
    <Folder Include="Areas\Assets\Controllers\" />
    <Folder Include="Areas\Assets\Models\" />
    <Folder Include="Areas\Assets\ViewModels\" />
    <Folder Include="Areas\Assets\Views\" />
    <Folder Include="Areas\User\Models\" />
    <Folder Include="Areas\User\ViewModels\" />
    <Folder Include="Areas\User\Views\" />
    <Folder Include="Services\Auth\" />
    <Folder Include="Services\Assets\" />
    <Folder Include="Services\Property\" />
    <Folder Include="Services\Storage\" />
    <Folder Include="Services\Notification\" />
  </ItemGroup>

</Project>
