// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocietyMng.Data;

#nullable disable

namespace SocietyMng.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250804103054_seedingdata")]
    partial class seedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocietyMng.Data.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("PropertyTypeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.SystemCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "User_Role",
                            Description = "User roles in the system"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Block",
                            Description = "Society blocks"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Property_Type",
                            Description = "Property types"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Asset_Status",
                            Description = "Asset statuses"
                        });
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.SystemCodeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("SystemCodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemCodeId");

                    b.ToTable("SystemCodeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Admin",
                            Description = "System Administrator",
                            IsActive = true,
                            SortOrder = 1,
                            SystemCodeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Buyer",
                            Description = "Property Buyer",
                            IsActive = true,
                            SortOrder = 2,
                            SystemCodeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "Sales",
                            Description = "Society Sales",
                            IsActive = true,
                            SortOrder = 3,
                            SystemCodeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "BLOCK_A",
                            Description = "Block A",
                            IsActive = true,
                            SortOrder = 1,
                            SystemCodeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "BLOCK_B",
                            Description = "Block B",
                            IsActive = true,
                            SortOrder = 2,
                            SystemCodeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = "BLOCK_C",
                            Description = "Block C",
                            IsActive = true,
                            SortOrder = 2,
                            SystemCodeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Code = "BLOCK_D",
                            Description = "Block D",
                            IsActive = true,
                            SortOrder = 2,
                            SystemCodeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = "APARTMENT",
                            Description = "Apartment",
                            IsActive = true,
                            SortOrder = 1,
                            SystemCodeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Code = "COMMERCIAL",
                            Description = "Commercial",
                            IsActive = true,
                            SortOrder = 2,
                            SystemCodeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Code = "LAND",
                            Description = "Land/Plot",
                            IsActive = true,
                            SortOrder = 2,
                            SystemCodeId = 3
                        },
                        new
                        {
                            Id = 11,
                            Code = "AVAILABLE",
                            Description = "Available",
                            IsActive = true,
                            SortOrder = 1,
                            SystemCodeId = 4
                        },
                        new
                        {
                            Id = 12,
                            Code = "BOOKED",
                            Description = "Booked",
                            IsActive = true,
                            SortOrder = 2,
                            SystemCodeId = 4
                        },
                        new
                        {
                            Id = 13,
                            Code = "SOLD",
                            Description = "Sold",
                            IsActive = true,
                            SortOrder = 3,
                            SystemCodeId = 4
                        });
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mishal@society.com",
                            FullName = "Mishal Ali",
                            Gender = "Female",
                            IsActive = true,
                            PasswordHash = "$2a$08$1m.DC2ZBSdrDYHzW/QiGJexNx9U7TlAuBaBsav6..pGLkh7zJT4Ym",
                            PhoneNumber = "1122334455",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.Asset", b =>
                {
                    b.HasOne("SocietyMng.Data.Entities.SystemCodeItem", "Block")
                        .WithMany("BlockAssets")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocietyMng.Data.Entities.SystemCodeItem", "PropertyType")
                        .WithMany("TypeAssets")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocietyMng.Data.Entities.SystemCodeItem", "Status")
                        .WithMany("StatusAssets")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocietyMng.Data.Entities.User", null)
                        .WithMany("UploadedAssets")
                        .HasForeignKey("UserId");

                    b.Navigation("Block");

                    b.Navigation("PropertyType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.Booking", b =>
                {
                    b.HasOne("SocietyMng.Data.Entities.Asset", "Asset")
                        .WithMany("Bookings")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocietyMng.Data.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.Complaint", b =>
                {
                    b.HasOne("SocietyMng.Data.Entities.Asset", "Asset")
                        .WithMany("Complaints")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SocietyMng.Data.Entities.Booking", "Booking")
                        .WithMany("Complaints")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SocietyMng.Data.Entities.User", "User")
                        .WithMany("Complaints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.SystemCodeItem", b =>
                {
                    b.HasOne("SocietyMng.Data.Entities.SystemCode", "SystemCode")
                        .WithMany("Items")
                        .HasForeignKey("SystemCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemCode");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.User", b =>
                {
                    b.HasOne("SocietyMng.Data.Entities.SystemCodeItem", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.Asset", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.Booking", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.SystemCode", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.SystemCodeItem", b =>
                {
                    b.Navigation("BlockAssets");

                    b.Navigation("StatusAssets");

                    b.Navigation("TypeAssets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Complaints");

                    b.Navigation("UploadedAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
