// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocietyMng.Data;

#nullable disable

namespace SocietyMng.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250730075932_seedingdata")]
    partial class seedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocietyMng.Data.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomCountId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomCountId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankAccount = "US1234567890123456",
                            ContactNumber = "555-0101",
                            Email = "john.smith@example.com",
                            FullName = "John Smith",
                            HireDate = new DateTime(2018, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Position = "Manager",
                            Salary = 65000.00m
                        },
                        new
                        {
                            Id = 2,
                            BankAccount = "US2345678901234567",
                            ContactNumber = "555-0102",
                            Email = "emily.j@example.com",
                            FullName = "Emily Johnson",
                            HireDate = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Position = "Accountant",
                            Salary = 55000.00m
                        },
                        new
                        {
                            Id = 3,
                            BankAccount = "US3456789012345678",
                            ContactNumber = "555-0103",
                            Email = "michael.w@example.com",
                            FullName = "Michael Williams",
                            HireDate = new DateTime(2020, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Position = "Maintenance Supervisor",
                            Salary = 48000.00m
                        },
                        new
                        {
                            Id = 4,
                            BankAccount = "US4567890123456789",
                            ContactNumber = "555-0104",
                            Email = "sarah.b@example.com",
                            FullName = "Sarah Brown",
                            HireDate = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Position = "Administrative Assistant",
                            Salary = 42000.00m
                        },
                        new
                        {
                            Id = 5,
                            BankAccount = "US5678901234567890",
                            ContactNumber = "555-0105",
                            Email = "robert.d@example.com",
                            FullName = "Robert Davis",
                            HireDate = new DateTime(2017, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Position = "Security Officer",
                            Salary = 38000.00m
                        },
                        new
                        {
                            Id = 6,
                            BankAccount = "US6789012345678901",
                            ContactNumber = "555-0106",
                            Email = "jennifer.m@example.com",
                            FullName = "Jennifer Miller",
                            HireDate = new DateTime(2022, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Position = "Community Manager",
                            Salary = 58000.00m
                        },
                        new
                        {
                            Id = 7,
                            BankAccount = "US7890123456789012",
                            ContactNumber = "555-0107",
                            Email = "david.w@example.com",
                            FullName = "David Wilson",
                            HireDate = new DateTime(2020, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Position = "Maintenance Technician",
                            Salary = 45000.00m
                        },
                        new
                        {
                            Id = 8,
                            BankAccount = "US8901234567890123",
                            ContactNumber = "555-0108",
                            Email = "lisa.t@example.com",
                            FullName = "Lisa Taylor",
                            HireDate = new DateTime(2019, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Position = "Accountant",
                            Salary = 53000.00m
                        });
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.SystemCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "User_Role",
                            Description = "User roles in the system"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Room_No",
                            Description = "Property room counts"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Asset_Status",
                            Description = "Rental/Sale statuses"
                        });
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.SystemCodeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("SystemCodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemCodeId");

                    b.ToTable("SystemCodeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Admin",
                            Description = "System Administrator",
                            IsActive = true,
                            SortOrder = 1,
                            SystemCodeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Resident",
                            Description = "Society Resident",
                            IsActive = true,
                            SortOrder = 2,
                            SystemCodeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "Buyer",
                            Description = "Property Buyer",
                            IsActive = true,
                            SortOrder = 3,
                            SystemCodeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "1_ROOM",
                            Description = "1 Bedroom",
                            IsActive = true,
                            SortOrder = 1,
                            SystemCodeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "2_ROOMS",
                            Description = "2 Rooms, 1 Kitchen",
                            IsActive = true,
                            SortOrder = 2,
                            SystemCodeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = "3_ROOMS",
                            Description = "3 Rooms, 1 Living room & 1 Kitchen",
                            IsActive = true,
                            SortOrder = 3,
                            SystemCodeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Code = "Rental_avail",
                            Description = "Available for Rent",
                            IsActive = true,
                            SortOrder = 1,
                            SystemCodeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Code = "Rented",
                            Description = "Rented",
                            IsActive = true,
                            SortOrder = 2,
                            SystemCodeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Code = "Sale_avail",
                            Description = "Available for Sale",
                            IsActive = true,
                            SortOrder = 3,
                            SystemCodeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Code = "Sold",
                            Description = "Sold",
                            IsActive = true,
                            SortOrder = 4,
                            SystemCodeId = 3
                        });
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@society.com",
                            FullName = "Mishal Ali",
                            Gender = "Female",
                            IsActive = true,
                            PasswordHash = "$2a$08$1m.DC2ZBSdrDYHzW/QiGJexNx9U7TlAuBaBsav6..pGLkh7zJT4Ym",
                            PhoneNumber = "1122334455",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.Asset", b =>
                {
                    b.HasOne("SocietyMng.Data.Entities.SystemCodeItem", "RoomCount")
                        .WithMany()
                        .HasForeignKey("RoomCountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocietyMng.Data.Entities.SystemCodeItem", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocietyMng.Data.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RoomCount");

                    b.Navigation("Status");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.Complaint", b =>
                {
                    b.HasOne("SocietyMng.Data.Entities.User", "User")
                        .WithMany("Complaints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.SystemCodeItem", b =>
                {
                    b.HasOne("SocietyMng.Data.Entities.SystemCode", "SystemCode")
                        .WithMany("Items")
                        .HasForeignKey("SystemCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemCode");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.User", b =>
                {
                    b.HasOne("SocietyMng.Data.Entities.SystemCodeItem", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.SystemCode", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SocietyMng.Data.Entities.User", b =>
                {
                    b.Navigation("Complaints");
                });
#pragma warning restore 612, 618
        }
    }
}
